### PR TITLE
Write directly to output without staging

### PR DESCRIPTION
**Pull request by mulby**
This now respects the "stage_output" attribute on output targets. When false, this prevents Luigi from writing to a temporary directory and then performing a move. Instead it will just write the output directly to the output directory.

It also adds support for a "prerpare_for_output()" method on output targets that let them run whatever checks, perform cleanup etc right before the job is actually run.

@brianhw

### CODE REVIEW

**Comment by mulby** [comment]
FYI jab5569

**Comment by brianhw** [comment]
LGTM.  

Just a small question of inverting logic: because the default behavior for most targets is to perform "staging", it felt backwards to set it to false to get non-default behavior.  Alternative is to flip it, and have something defined as "disable_staging", and set that to true to get non-default behavior.  Maybe there's a better name, and one that is a more positive form:  e.g. "enable_direct_output".

**Comment by mulby** [comment]
@brianhw can you review this again? I'm planning on merging this as part of the hotfix. Note that I've changed it to look at an attribute of the job, not the output target since that is much easier to work with downstream.

**Comment by brianhw** [comment]
LGTM.  I also looked at the current Luigi implementation, and they had the opposite flag (end_job_with_atomic_move_dir, with a True default), but as a property on the Runner instead of on the job.  So if we're not going to do exactly that, I'm fine with putting in something that works for now, and change it when we upgrade.  It shouldn't be too much code.  :+1:

**Comment by mulby** [comment]
I like having the flag at the job level. My current thinking is that we can continue to use the job level flag for the time being, but when we upgrade we can modify the runner to use the end_job_with_atomic_move_dir flag if enable_direct_output is set on the job. Something like:

```python
# In the map reduce job runner
self.end_job_with_atomic_move_dir = not job.enable_direct_output
```

**Pull request merged**
