### PR TITLE
pull in egg-info for any used package

### PR DESCRIPTION
**Pull request by mulby**

### CODE REVIEW

**Comment by brianhw** [comment]
Looks good generally.  

I'm curious what it should/would do when confronted with the original situation we had.  Here's what I have in my virtualenv:
edx_opaque_keys-0.2.1-py2.7.egg-info
opaque_keys-0.1.2-py2.7.egg-info
opaque_keys

This situation arose because the pipeline had installed opaque_keys, and ccx-keys had installed edx_opaque_keys, and each of these installed opaque_keys.  The order of these depends on whether the -e flag is used when loading a particular hash -- if the flag is used, then it will be loaded last (i.e. take precedence); if not, then it goes in order (I think), and in this case the edx_opaque_keys was loaded after opaque_keys.

Either way, both of the egg-info directories contain a SOURCES.txt file that includes all of the files in opaque_keys.  So the way this code is currently written, the metadata that is used is somewhat arbitrary in terms of the order that the dist code returns packages.  And that the last of the packages wins.

**Comment by brianhw** [comment]
@mulby I've updated the tests now, with minimal changes to the regular code.  I've not done anything to mess with the version in setup.py, however.  I propose merging this to release (and not bothering with master), and updating the hash used by pipeline, and tagging with the edx.3 suffix.

**Comment by mulby** [comment]
:+1: 

I agree with the approach for merging, tagging etc.

**Comment by mulby** [comment]
Also, thanks for adding the test, this is much better!

**Pull request merged**
