### PR TITLE
Removed CI checks from repo

### PR DESCRIPTION
**Pull request by aht007**
Issue: [BOM-2994](https://openedx.atlassian.net/browse/BOM-2994)

### Description
- Removed `Travis.yml` since `Travis` has been migrated to `GitHub Actions` across `edX`.
- Spent time trying to fix the failures in the `GitHub CI` but the failures couldn't be fixed so according to the owning team's suggestion, the `GitHub CI` skipped for now to complete the `Travis` removal task.

### CODE REVIEW

**Comment by estute** [comment]
I think you forgot to add the deletion of the .travis.yml file.

**Comment by estute** [comment]
@aht007 You will need to remove the .travis.yml file as well. Aside from that, is this good to review?

**Comment by estute** [comment]
Seems like a lot of the jobs are failing. Let's get those fixed as well. I'll take a stab at creating a fork of this and getting them working tomorrow.

**Comment by estute** [comment]
I'm not sure what's going on here. It looks like the GH Actions were cancelled.

**Comment by UsamaSadiq** [comment]
As per the discussion with the owning team, this repo isn't being maintained much so we can remove checks from CI since it took us a long time trying to fix the failures.

**Comment by aht007** [comment]
@UsamaSadiq Why is there a need for empty CI file...? Shouldn't we just remove travis file and add nothing here?

**Review by estute — COMMENTED** [review]
Right. Please delete the file and I'll approve it and close out the support ticket linked to this

**Review by estute — APPROVED** [review]

**Pull request merged**
